language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t piter765/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true piter765/react-test npm test

after_success:
  - docker build -t piter765/multi-client ./client
  - docker build -t piter765/multi-nginx ./nginx
  - docker build -t piter765/multi-server ./server
  - docker build -t piter765/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  - docker push piter765/multi-client
  - docker push piter765/multi-nginx
  - docker push piter765/multi-server
  - docker push piter765/multi-worker
