language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t piter765/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true piter765/react-test npm test

after_success:
  - docker build -t piter765/multi-client ./client
  - docker build -t piter765/multi-nginx ./nginx
  - docker build -t piter765/multi-server ./server
  - docker build -t piter765/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  - docker push piter765/multi-client
  - docker push piter765/multi-nginx
  - docker push piter765/multi-server
  - docker push piter765/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: 'us-east-1'
    app: 'multi-docker'
    env: 'Multi-docker-env'
    bucket_name: 'elasticbeanstalk-us-east-1-752652870392'
    bucket-path: 'docker-multi'
    on:
      branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

